#!/usr/bin/env node

// This file simulates 'npm start' for deployment systems that expect it

import { execSync } from 'child_process';

try {
  console.log('Running start script...');
  execSync('./scripts/start.sh', { stdio: 'inherit' });
} catch (error) {
  console.error('Start failed:', error);
  process.exit(1);
}