services:
  - type: web
    name: telemed-sistema
    env: node
    buildCommand: node build.js
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          property: port