#!/bin/bash
echo "=== TELEMED DEPLOYMENT VERIFICATION ==="
echo "📁 Publish Directory: public_live"
echo "🏠 Homepage: lp.html"
echo ""
echo "📊 Route Structure:"
ls -la public_live/*/index.html 2>/dev/null | wc -l | awk '{print "Routes with content: " $1}'
echo ""
echo "📦 Assets:"
echo "CSS files: $(find public_live/css -name "*.css" 2>/dev/null | wc -l)"
echo "JS files: $(find public_live/js -name "*.js" 2>/dev/null | wc -l)"
echo "Images: $(find public_live/assets public_live/images public_live/img -type f 2>/dev/null | wc -l)"
echo ""
echo "🔗 Key Files:"
[ -f "public_live/lp.html" ] && echo "✅ Homepage (lp.html)" || echo "❌ Homepage missing"
[ -f "public_live/dashboard/index.html" ] && echo "✅ Dashboard" || echo "❌ Dashboard missing"
[ -f "public_live/css/theme-telemed.css" ] && echo "✅ TeleMed theme" || echo "❌ Theme missing"
[ -f "render.yaml" ] && echo "✅ Render config" || echo "❌ Render config missing"
echo ""
echo "🚀 Ready for Render deployment!"
